version: '3.3'
services:
  web:
    depends_on:
      - db
    build:
      context: ./php
      dockerfile: dockerfile
    container_name: php73
    volumes:
      - ./php:/var/www/html/
    ports:
      - '8080:80'
  db:
    container_name: mysql8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: cityofhayward
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - '3306:3306'
    security_opt:
      - seccomp:unconfined
  selenium:
    image: selenium/hub
    ports:
      - '4444:4444'
  chromenode:
    image: selenium/node-chrome-debug
    ports:
      - '4557'
    links:
      - selenium:hub


