FROM php:8.0.3-apache-buster
RUN apt update && apt-get upgrade -y
RUN docker-php-ext-install mysqli
EXPOSE 80
RUN docker-php-ext-install pdo pdo_mysql
RUN a2enmod rewrite
COPY php.ini /usr/local/etc/php/php.ini
